"""empty message

Revision ID: 450fc41d5650
Revises: 
Create Date: 2023-02-12 15:06:25.019923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '450fc41d5650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_model',
    sa.Column('image_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('input_image_url', sa.VARCHAR(), nullable=False),
    sa.Column('output_image_url', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('user_model',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.VARCHAR()), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    op.drop_table('image_model')
    # ### end Alembic commands ###
