from os import environ
class EnvironmentVariables:
    REFRENCE_IMAGE_URL="REFRENCE_IMAGE_URL"
    JWT_SECRET="JWT_SECRET"
    ADMIN_USER="ADMIN_USER"
    ADMIN_EMAIL="ADMIN_EMAIL"
    ADMIN_PASSWORD="ADMIN_PASSWORD"
    CLOUDINARY_CLOUD_NAME="CLOUDINARY_CLOUD_NAME"
    CLOUDINARY_CLOUD_API_KEY="CLOUDINARY_CLOUD_API_KEY"
    CLOUDINARY_CLOUD_API_SECRET="CLOUDINARY_CLOUD_API_SECRET"


    def get_environment_variable(name:str):
        return environ[name]